In [1]:
import pandas as pd
import numpy as np

np.__version__

'1.26.3'

In [2]:
#import pandas as pd

#list of strings
lst = ["Geeks", "For", "Geeks", "is", "portal", "for", "Geeks"]

#Calling DataFrame constructor on list
df = pd.DataFrame(lst)
print(df)


        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks


## Loading libraries

In [5]:
# Create a data Frame - Dictionary is used here where keys 
# keys get converted to column names and values to row values

data = pd.DataFrame({'Country':["Russia", "Colombia", "Chile", "Equador", "Nigeria"], "Rank": [121, 40, 100, 130, 11]})
print(data)

    Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11


In [10]:
# Quick Analysis of any data set
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [11]:
# We can also show show some information about the data set

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes


In [13]:
# Let's create another data frame.

data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

print(data)

  group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0


In [14]:
#Sorting the data frame by ounces-inplace = True
#will make changes to the data

data.sort_values(by=['ounces'], ascending=True, inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [15]:
# We can also sort the data by not just one column but multiple columns
data.sort_values(by=['group','ounces'], ascending=[True, False], inplace=False)

group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [25]:
#How to get rid of the duplicate values and inconsistencies
#Let's create a new data

data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
print(data)

#Sorting values
sortedData = data.sort_values(by="k2")
#print("\nThe sorted values are:\n", sortedData)

#removing duplicate values
removedDuplicate = data.drop_duplicates()
#print("\nData without duplicated values\n", removedDuplicate)

#removing duplicates based on a particular coumn
removedDuplicate = data.drop_duplicates(subset="k1")
print("\nRemoved duplicates based on a \nparticular column and subset\n", removedDuplicate)

    k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4
Removed duplicates based on a particular column and subset
     k1  k2
0  one   3
3  two   3


In [26]:
''' 
create a new variable which indicates the type of animal
which acts as the source of the food. To do that, first 
we'll create a dictionary to map the food to the animals. 
Then, we'll use map function to map the dictionary's values
 to the keys. Let's see how is it done.
'''
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'honey ham':
        return 'pig'
    else:
        return 'salmon'
    

# Create a new variable
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
print(data)

KeyError: 'food'

In [18]:
#Python code demonstrate creating
#DataFrame from dict and array/lists
#By default addresses

#initialize data of lists.
data = {'Name': ['Tom', 'nick', 'krish', 'Jack'], 'Age':[20, 21, 19, 24]}

#create DataFrame
df = pd.DataFrame(data)

#Printing the output
print(df)


    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   Jack   24


In [4]:
# Import pandas package

# Define a dictionary containing employee data
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
    'Age':[27, 24, 22, 32],
    'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
    'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

# Convert the dictionary into DataFrame 
df = pd.DataFrame(data)

# Selecting all columns
print(df)

# select two columns
print(df[['Name', 'Qualification']])

     Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           Phd
     Name Qualification
0     Jai           Msc
1  Princi            MA
2  Gaurav           MCA
3    Anuj           Phd


## Simple Operation using numpy Library 2/8/2024

In [12]:

#Checking the version of the installed numpy
np.__version__


#Create a list comprising numbers from 0 to 9
L = list(range(10))

[type(item) for item in L]

[int, int, int, int, int, int, int, int, int, int]

In [37]:
# Function for printing the elements of the array

# Creating Arrays
arr0 = np.zeros(10, dtype='int')
print(arr0)

# Creating a 3 row x 5 column matrix
arr1 = np.ones((3, 5), dtype='float')
print(arr1)

# Creating a matrix with predifined value
arr2 = np.full((3, 5), 1.23)
print(arr2)

# Create an array with a set sequence
arr3 = np.arange(0, 30, 2)
print(arr3)

# Create an array of even space between the given range of values
arr4 = np.linspace(0, 1, 5)
print(arr4)

# Create an Identity matrix
arr5 = np.eye(3)
print(arr5)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
# Array and indexing
# We will use the previously created value

# Access value to index zero

arr0[0]

# Access fith value
arr3[5]

# Get the last value in the array
arr3[-1]

# Get the second last value in the array
arr3[-2]

# In case of multidimensional matrix
x2 = np.array([[3, 7, 5, 5], [10, 1, 5, 9], [3, 7, 5, 2]])

# 1st row and second column value

x2[0,1]

# 3rd row and last value from the 3rd column
x2[2, -1]

# replace value at 0, 0 index
x2[0,0] = 12
x2

array([[12,  7,  5,  5],
       [10,  1,  5,  9],
       [ 3,  7,  5,  2]])

In [51]:
# Array Slicing

x = np.arange(10)
x

# from start to 4th position
x[:5]

# from 4th position to end
x[4:]

# from 4th to 6th position
x[4:7]

# return elements at even place
x[ : : 2]

# return elements from first position step by two
x[1::2]

# reverse the array
x[::-1]



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [56]:
# Array Concatenation

# You can concatenate two or more arrays at once.

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21, 21, 21]

np.concatenate([x, y, z])

# You can also use this function to create 2-dimensional arrays.
grid = np.array([[1, 2, 3], [3, 2, 1]])

np.concatenate([grid, grid])

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [57]:
# Using vstack or hstack for combining array
# That does not have egal dimension

x = np.array([3, 4, 5])
grid = np.array([[1, 2, 3],[17, 18, 19]])

np.vstack([x, grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])